### ISSUE TITLE
關於這個專案的授權

### ISSUE THREAD

**Issue by DoubleAix** [Bearscience/Time-NLPY#2]
hi, @Bearscience
我這邊有個需求，我想要把簡體改成繁體，包括一些字和規則的修改以符合我們繁體使用者的需求，是否可以直接把你的程式碼複製到我的repo，而不透過fork的方式？那假如我能複製，我需要標注什麼嗎？

我會有疑惑是因為我在setup.py看到license是MIT，但一般授權應該會另外寫出來

謝謝！！！

**Comment by Bearscience** [comment]
程序版权归原作者https://github.com/sunfiyes所有，按照setup许可证授权即可。
